trigger:
- main

pool:
  vmImage: ubuntu-latest
  
resources:
  repositories:
    - repository: templates
      type: git
      name: Codat/YAMLBuildTemplates

stages:
  - template: Build/Frontend.yml@templates
    parameters:
      AppName: DemoLinkApp
      ArtifactName: DemoLinkApp
      ArchiveArtifact: true
      SkipUnitTests: true
      RunCypressComponentTests: false
      CypressComponentTestsScript: false
      CypressIntegrationTestsScript: false
      RunCypressIntegrationTests: false
      CombineTestCoverage: false
      ConfigExistingLocation: server/.env.template
      ConfigNewLocation: server/.env