trigger:
- main

pool:
  vmImage: ubuntu-latest
  
resources:
  repositories:
    - repository: templates
      type: git
      name: Codat/YAMLBuildTemplates

stages:
  - template: Build/Frontend.yml@templates
    parameters:
      AppName: Demo Link App
      ArtifactName: PortalUI
      ArchiveArtifact: true
      RunCypressComponentTests: true
      TypeCheckScript: check-types
      SkipUnitTests: true