trigger:
- main

pool:
  vmImage: ubuntu-latest
  
resources:
  repositories:
    - repository: templates
      type: git
      name: Codat/YAMLBuildTemplates

stages:
  - template: Build/Frontend.yml@templates
    parameters:
      AppName: DemoLinkApp
      ArtifactName: DemoLinkApp
      ArchiveArtifact: true
      RunCypressComponentTests: false
      TypeCheckScript: check-types
      SkipUnitTests: true